version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "ukwhatn"

  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "develop"
    versioning-strategy: increase-if-necessary
    assignees:
      - "ukwhatn"

  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "daily"
    target-branch: "develop"
    assignees:
      - "ukwhatn"
