# Dev environment (auto-deploy via Watchtower)
# Image from GHCR.io (develop tag)
# Database: Local (POSTGRES_HOST=db) or External (DBaaS like Supabase)
# No port exposure (use Cloudflare Tunnels)
#
# Usage:
#   make dev:deploy  # Initial deployment
#   make dev:logs    # View logs
#   make dev:ps      # Check status

services:
  server:
    container_name: ${COMPOSE_PROJECT_NAME:-fastapi-template}-server-dev
    image: ghcr.io/${GITHUB_REPOSITORY:-ukwhatn/fastapi-template}:develop
    command:
      - /bin/sh
      - -c
      - |
        fastapi run app/main.py --host 0.0.0.0 --port 80 --proxy-headers
    volumes:
      - ./newrelic.ini:/etc/newrelic.ini:ro
    env_file:
      - .env
    environment:
      - ENV_MODE=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/system/healthcheck/"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      db:
        condition: service_healthy
        required: false
    networks:
      - db-dev
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  db:
    container_name: ${COMPOSE_PROJECT_NAME:-fastapi-template}-db-dev
    image: postgres:17
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-main}
      TZ: Asia/Tokyo
    volumes:
      - pg_data_dev:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-user} -d ${POSTGRES_DB:-main}
      interval: 2s
      timeout: 5s
      retries: 30
    networks:
      - db-dev
    profiles:
      - local-db
    labels:
      - "com.centurylinklabs.watchtower.enable=false"

volumes:
  pg_data_dev:
    name: ${COMPOSE_PROJECT_NAME:-fastapi-template}-pg-data-dev

networks:
  db-dev:
    name: ${COMPOSE_PROJECT_NAME:-fastapi-template}-db-dev
    driver: bridge
