name: 'Setup Python with uv'
description: 'Set up Python environment using uv with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.13'
  cache-dependency-glob:
    description: 'Glob pattern for cache dependency files'
    required: false
    default: 'uv.lock'

runs:
  using: 'composite'
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v7
      with:
        enable-cache: true
        cache-dependency-glob: ${{ inputs.cache-dependency-glob }}

    - name: Set up Python
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: uv python install "$PYTHON_VERSION"

    - name: Install dependencies
      shell: bash
      run: uv sync --all-groups
