name: Deploy to Stg

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/cd_builder.yml
    secrets: inherit

  deploy:
    needs: build-and-push
    uses: ./.github/workflows/cd_deliverer.yml
    with:
      environment: stg
      branch: develop
      image_tag: develop
    secrets:
      SSH_HOST: ${{ secrets.STG_SSH_HOST }}
      SSH_USER: ${{ secrets.STG_SSH_USER }}
      SSH_PORT: ${{ secrets.STG_SSH_PORT }}
      SSH_PRIVATE_KEY: ${{ secrets.STG_SSH_PRIVATE_KEY }}
