name: Lint

on:
  workflow_call:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-uv

      - name: Run linting checks
        run: |
          make lint &
          LINT_PID=$!

          make format:check &
          FORMAT_PID=$!

          wait $LINT_PID || exit 1
          wait $FORMAT_PID || exit 1
