name: Security Scan

on:
  workflow_call:
  workflow_dispatch:

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-uv

      - name: Run security scans
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin v0.46.1 &
          TRIVY_INSTALL_PID=$!

          make security:scan:code:critical &
          BANDIT_PID=$!

          make security:scan:sast:critical &
          SEMGREP_PID=$!

          wait $TRIVY_INSTALL_PID

          make security:scan:trivy &
          TRIVY_PID=$!

          wait $BANDIT_PID || exit 1
          wait $SEMGREP_PID || exit 1
          wait $TRIVY_PID || exit 1
