name: Unit Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 1

      - name: Setup Python with uv
        uses: ./.github/actions/setup-python-uv

      - name: Run tests with coverage
        run: |
          make test
